[settings]
node_spawn_timeout = 240

[relaychain]
default_command = "{{POLKADOT_BINARY}}"
default_args = ["-lparachain=debug,xcm=trace"]
chain = "polkadot-local"
chain_spec_command = "{{CHAIN_SPEC_GEN_BINARY_FOR_POLKADOT}} {% raw %} {{chainName}} {% endraw %}"

[[relaychain.nodes]]
name = "alice"
validator = true
rpc_port = 9942
balance = 2000000000000

[[relaychain.nodes]]
name = "bob"
validator = true
rpc_port = 9943
balance = 2000000000000

[[relaychain.nodes]]
name = "charlie"
validator = true
rpc_port = 9944
balance = 2000000000000

[[parachains]]
id = 1002
chain = "people-hub-polkadot-local"
chain_spec_command = "{{ENV_PATH}}/generate_php_spec.sh Kusama {% raw %} {{chainName}} {% endraw %}"
cumulus_based = true

[[parachains.collators]]
name = "people-hub-polkadot-collator-1"
validator = true
command = "{{POLKADOT_PARACHAIN_BINARY}}"
rpc_port = 8943
args = [
	"-lparachain=debug,runtime::bridge-hub=trace,runtime::bridge=trace,runtime::bridge-dispatch=trace,bridge=trace,runtime::bridge-messages=trace,xcm=trace",
]

[[parachains.collators]]
name = "people-hub-polkadot-collator-2"
validator = true
command = "{{POLKADOT_PARACHAIN_BINARY}}"
rpc_port = 8944
args = [
	"-lparachain=trace,runtime::bridge-hub=trace,runtime::bridge=trace,runtime::bridge-dispatch=trace,bridge=trace,runtime::bridge-messages=trace,xcm=trace",
]
