# https://www.npmjs.com/package/@zombienet/cli
# To run the network, execute the following command:
# zombienet -p native spawn ./zombienet/config.toml

[relaychain]
chain = "local"
default_command = "{{POLKADOT_BULLETIN_BINARY_PATH}}"

	[[relaychain.nodes]]
	name = "alice"
	rpc_port = 10000
	validator = true
	args = [ "--ipfs-server", "-lruntime=trace,runtime::bridge-hub=trace,runtime::bridge=trace,runtime::bridge-dispatch=trace,bridge=trace,runtime::bridge-messages=trace", "-lxcm=trace" ]

	[[relaychain.nodes]]
	name = "bob"
	rpc_port = 10001
	validator = true
